print('')
print('Agora vamos converter "Metros" em "Centímetros" e em "Milímetros"!')
metros = float(input('Para isso, preciso que me passe uma medida em Metros: '))
print('Obrigado!')
print('')
print('Calculando...')
print('')
print('{}m convertido em Centrímetros fica em: {}cm!'.format(metros, (metros*100)))
print('{}m convertido em Milímetros fica em: {}mm!'.format(metros, (metros*1000)))